
export default new Map([
["src/content/blog/get-cited-in-chatgpt.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fget-cited-in-chatgpt.mdx&astroContentModuleFlag=true")],
["src/content/blog/aeo-answer-engine-optimization-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Faeo-answer-engine-optimization-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/geo-vs-seo-2026.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fgeo-vs-seo-2026.mdx&astroContentModuleFlag=true")],
["src/content/blog/google-ai-overviews-optimization.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fgoogle-ai-overviews-optimization.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-get-cited-in-chatgpt.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-get-cited-in-chatgpt.mdx&astroContentModuleFlag=true")],
["src/content/blog/lighthouse-100-blueprint.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Flighthouse-100-blueprint.mdx&astroContentModuleFlag=true")],
["src/content/blog/llms-txt-explained.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fllms-txt-explained.mdx&astroContentModuleFlag=true")],
["src/content/blog/llms-txt-setup-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fllms-txt-setup-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/optimize-for-perplexity.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Foptimize-for-perplexity.mdx&astroContentModuleFlag=true")],
["src/content/blog/perplexity-seo-strategy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fperplexity-seo-strategy.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/coffee-shop-ai-visuals.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fcoffee-shop-ai-visuals.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/ecommerce-ai-visibility.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fecommerce-ai-visibility.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/dental-chain-local-seo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fdental-chain-local-seo.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/saas-platform-rebuild.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fsaas-platform-rebuild.mdx&astroContentModuleFlag=true")],
["src/content/blog/programmatic-local-seo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fprogrammatic-local-seo.mdx&astroContentModuleFlag=true")],
["src/content/blog/voice-search-optimization-2026.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fvoice-search-optimization-2026.mdx&astroContentModuleFlag=true")],
["src/content/blog/what-is-geo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhat-is-geo.mdx&astroContentModuleFlag=true")]]);
		