name = "rex-bunny-services"
compatibility_date = "2026-07-03"
compatibility_flags = ["global_fetch_strictly_public"]

pages_build_output_dir = "dist"

[env.production]
name = "rexbunnyservices"

[env.preview]
name = "rexbunnyservices-preview"
