[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "R3xBunnyL1stMonk!2024$"

[db]
host = "listmonk-db"
port = 5432
user = "listmonk"
password = "L1stMonkD3lt@5ecur3P4ssw0rd!"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
database = "listmonk"

[smtp]
enabled = true
host = "smtpout.secureserver.net"
port = 465
auth_protocol = "smtp"
username = "help@rexbunnyservices.online"
password = "Rexbunny@786"
